name: CI

on:
  push:
    branches:
      - master

jobs:
  unit_test:
    name: Run unit tests with Karma and Jasmine
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install --prefix openvidu-call-front
    - name: Unit Tests
      run: npm run test --prefix openvidu-call-front